# Spectra config file (bundled; v{SPECTRA_CURRENT_VERSION})


# Configuration for Spectra
# -------------------------
[service]

# Determines the place where Spectra stores its data.
data_dir = "data"

# The IP address on which the service listens.
host = "127.0.0.1"

# The port on which the service listens.
port = 3000
