# Spectra config file (bundled; v0.1.0)


# Configuration for Spectra
# -------------------------
[service]

# Determines the place where Spectra stores its data
data_dir = "data"

# The key for encrypting cookies
cookie_key = "C0#yL!cDo*ajCl-d3bk9mrdxMFr!G-kfB@ExExDyRbB9l%pF24&sQ81ndl)E0-lf"

# The time to refresh the database, i.e. to mark expired items as unavailable
# and remove items that are no longer needed. Note that this should be a cron
# expression, otherwise Spectra would fail to launch.
refresh_time = "0 0 4 * * ?"


# Configuration for Cloudflare Turnstiles
# ---------------------------------------
[turnstile]

# Whether to enable Cloudflare Turnstile
# WARNING: Disabling this will prevent anonymous item creation
enabled = true

# Note: default values are for testing; you should replace them with your own
# Get one at https://dash.cloudflare.com/?to=/:account/turnstile
site_key = "1x00000000000000000000AA"
secret_key = "1x0000000000000000000000000000000AA"
